version: "3.7"

services:
    # Laravel Application
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # Nginx Service
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # PostgreSQL Database
    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE:-laravel}
            POSTGRES_USER: ${DB_USERNAME:-username}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
        volumes:
            - ./.docker/postgres/dbdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
